services:
  app:
    image: ghcr.io/zxw7608/help_to_learn:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./cookies.txt:/app/cookies.txt
    environment:
      - SITE_BASE_URL=https://yourdomain.com
