"""add material_type

Revision ID: c5c513b6569a
Revises: b1c2d3e4f5a7
Create Date: 2026-05-05 13:32:37.022025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5c513b6569a'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'material_type',
            sa.String(16),
            nullable=False,
            server_default='main',
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('material_type')

    # ### end Alembic commands ###
